# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

notifications:
  email:
    if: branch = master
    on_success: change
    on_failure: always
services:
  - docker

# include the following block if the C/C++ build artifacts should get cached by Travis,
# CCACHE_DIR needs to get set as well to actually fill the cache
cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true # optional, silences the cloning of the target repository

# configure the build environment(s)
# https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#variables-you-can-configure
env:
  global: # global settings for all jobs
    - ROS_REPO=testing
    - CCACHE_DIR=$HOME/.ccache # enables C/C++ caching in industrial_ci
  matrix: # each line is a job
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="melodic" OS_NAME=ubuntu OS_CODE_NAME=bionic
    - ROS_DISTRO="melodic" OS_NAME=debian OS_CODE_NAME=stretch

# allow failures, e.g. for unsupported distros
matrix:
  allow_failures:
    - env: ROS_DISTRO="indigo"

# clone and run industrial_ci
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
